### ISSUE TITLE
Some fuzzy .vue-files with alphanumeric string

### ISSUE THREAD

**Issue by Tomblarom** [kasparsd/besst-reference#1]
First of all, thank you for that writeup and your blog post. I tried to compile BESST based on [these sources](https://github.com/OpenSourceEBike/Bafang_M500_M600/tree/main/BESST/src), but never figured out how to decompile it from `exe`, so thanks for publishing!

However, when I tried recompiling the generated sources, there where always strange files, that seemed not full decompiled. `file.vue[4 letter alphanumeric string]` Do you know why that is?

![image](https://github.com/kasparsd/besst-reference/assets/12703270/cbd88557-c5cc-40ef-8816-6dbd8e08c9b1)

**Comment by kasparsd** [comment]
Those appear to be the [virtual DOM render functions](https://vuejs.org/guide/extras/rendering-mechanism.html) for the Vue components. For example, this render function:

https://github.com/kasparsd/besst-reference/blob/47b3139c6dc672b90358e546abc30992b20d48c9/app/static/js/webpack/src/components/tool/battery.vuee288#L13-L18

appears to map to this template string:

https://github.com/kasparsd/besst-reference/blob/47b3139c6dc672b90358e546abc30992b20d48c9/app/static/js/webpack/battery.vue#L5

There is a useful tool for browsing the source maps https://evanw.github.io/source-map-visualization/ -- I uploaded https://github.com/kasparsd/besst-reference/blob/47b3139c6dc672b90358e546abc30992b20d48c9/app/static/js/app.ed3de9b5d8365be3fcbc.js and the associated map file which produced:
 
![app](https://github.com/kasparsd/besst-reference/assets/169055/9b40654a-7e06-4e7d-8494-cb5772688854)
